### ISSUE TITLE
我创建了个monorepo，然后打包以后一些功能直接失效了💔

### ISSUE THREAD

**Issue by limuen** [ErKeLost/turborepo-template#18]
我创建了个monorepo，本地一切正常，然后打包以后一些功能直接失效了💔

**Comment by ErKeLost** [comment]
功能失效可能是 
1. 打包工具构建的问题
2. package json publish 的 file 字段定义的对么

跟 monorepo 应该没有关系的

或者你搞个 demo 我可以帮你看看

**Comment by limuen** [comment]
[我这里有一个私人库](https://monorepofe.vercel.app) 这是预览地址，更换主题暗黑模式里面一些功能bug

**Comment by ErKeLost** [comment]
> [我这里有一个私人库](https://monorepofe.vercel.app) 这是预览地址，更换主题暗黑模式里面一些功能bug

嗷嗷 你是web 的项目 正常 dev 没有问题 生产也不该有问题的 应该还是构建工具的事

**Comment by limuen** [comment]
能帮我看下一下吗 https://github.com/limuen/monorepoFE/invitations 这个仓库邀请你了 麻烦啦

**Comment by ErKeLost** [comment]
> 能帮我看下一下吗 https://github.com/limuen/monorepoFE/invitations 这个仓库邀请你了 麻烦啦

我有时间帮你看一下哈 主要你这个是功能问题 不是仓库结构问题

**Comment by limuen** [comment]
好好好 麻烦啦 十分感谢 那我就关闭这个issues了 或者给个联系方式 到时候也好请教你

**Comment by ErKeLost** [comment]
> 好好好 麻烦啦 十分感谢 那我就关闭这个issues了 或者给个联系方式 到时候也好请教你

好滴 好滴 可以加我微信 y1256029807
